[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
basics = "8bF8ZvmrBfXM8F3Bdks4YvgoyCjDHxbEjPLJhzn8E9oW"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/jogeshwar/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
